name: Android APK Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Permission to gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: |
          mkdir release
          cp app/build/outputs/apk/debug/app-debug.apk release/abhyas.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.${{ github.run_number }}
          name: Build v1.${{ github.run_number }}
          files: release/abhyas.apk
